version: '3.1'

services:
  db_user:
    image: postgres:latest
    container_name: user_auth_db
    volumes:
      - ./backend/user_auth_service/db/sql/tables:/sql_tables
      - ./backend/user_auth_service/db/sql/initdb:/docker-entrypoint-initdb.d
      - ./tmp/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: resellio_db
    ports:
      - "5432:5432"

  auth_service:
    build:
      context: ./backend/user_auth_service
    container_name: user_auth_service
    depends_on:
      - db_user
    environment:
      POSTGRES_HOST: db_user
    ports:
      - "8000:8000"
    volumes:
      - ./backend/user_auth_service:/app
