version: '3.1'

services:
  db:
    image: postgres:latest
    container_name: postgres-resellio
    volumes:
      - ./sql/tables:/sql_tables
      - ./sql/initdb:/docker-entrypoint-initdb.d
      - ./tmp/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: resellio_db
    ports:
      - "5432:5432"
