version: '3.1'

services:
  db_user:
    image: postgres:latest
    container_name: user_auth_db
    volumes:
      - ./backend/user_auth_service/db/sql/tables:/sql_tables
      - ./backend/user_auth_service/db/sql/initdb:/docker-entrypoint-initdb.d
      - ./tmp/user_auth_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: resellio_db
    ports:
      - "5433:5433"

  db_event_ticketing:
    image: postgres:latest
    container_name: event_ticketing_db
    volumes:
      - ./backend/user_auth_service/db/sql/tables:/sql_tables
      - ./backend/user_auth_service/db/sql/initdb:/docker-entrypoint-initdb.d
      - ./tmp/event_ticketing_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: resellio_event_ticketing_db
    ports:
      - "5432:5432"

  user_auth_service:
    build:
      context: ./backend/user_auth_service
    container_name: user_auth_service
    depends_on:
      - db_user
    environment:
      POSTGRES_HOST: db_user
    ports:
      - "8000:8000"
    volumes:
      - ./backend/user_auth_service:/app

  event_ticketing_service:
    build:
      context: ./backend/event_ticketing_service
    container_name: event_ticketing_service
    depends_on:
      - db_event_ticketing
    environment:
      POSTGRES_HOST: db_event_ticketing
    ports:
      - "8001:8001"
    volumes:
      - ./backend/event_ticketing_service:/app
