version: '3.1'
services:
  user_auth_db:
    image: postgres:latest
    container_name: user_auth_db
    volumes:
      - ./backend/user_auth_service/db/sql/tables:/sql_tables
      - ./backend/user_auth_service/db/sql/initdb:/docker-entrypoint-initdb.d
      - ./tmp/user_auth_db:/var/lib/postgresql/data
    env_file:
      - backend/user_auth_service/.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d resellio_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  event_ticketing_db:
    image: postgres:latest
    container_name: event_ticketing_db
    volumes:
      - ./backend/event_ticketing_service/db/sql/tables:/sql_tables
      - ./backend/event_ticketing_service/db/sql/initdb:/docker-entrypoint-initdb.d
      - ./tmp/event_ticketing_db:/var/lib/postgresql/data
    environment:
      PGPORT: 5433
    env_file:
      - backend/event_ticketing_service/.env
    ports:
      - "5433:5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d resellio_event_ticketing_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  user_auth_service:
    build:
      context: ./backend/user_auth_service
    container_name: user_auth_service
    depends_on:
      user_auth_db:
        condition: service_healthy
    env_file:
      - backend/user_auth_service/.env
    expose:
      - "8000"
    volumes:
      - ./backend/user_auth_service:/app

  event_ticketing_service:
    build:
      context: ./backend/event_ticketing_service
    container_name: event_ticketing_service
    depends_on:
      event_ticketing_db:
        condition: service_healthy
    env_file:
      - backend/event_ticketing_service/.env
    expose:
      - "8001"
    volumes:
      - ./backend/event_ticketing_service:/app

  api_gateway:
    build:
      context: ./backend/api_gateway
    container_name: api_gateway
    depends_on:
      - user_auth_service
      - event_ticketing_service
    env_file:
      - "backend/api_gateway/.env"
    ports:
      - "8080:8080"  # Expose gateway to host
    volumes:
      - ./backend/api_gateway:/app
