version: '3.1'

services:
  user_auth_db:
    image: postgres:latest
    container_name: user_auth_db
    volumes:
      - ./backend/user_auth_service/db/sql/tables:/sql_tables
      - ./backend/user_auth_service/db/sql/initdb:/docker-entrypoint-initdb.d
      - ./tmp/user_auth_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: resellio_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d resellio_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  event_ticketing_db:
    image: postgres:latest
    container_name: event_ticketing_db
    volumes:
      - ./backend/event_ticketing_service/db/sql/tables:/sql_tables
      - ./backend/event_ticketing_service/db/sql/initdb:/docker-entrypoint-initdb.d
      - ./tmp/event_ticketing_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: resellio_event_ticketing_db
      PGPORT: 5433
    ports:
      - "5433:5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d resellio_event_ticketing_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  user_auth_service:
    build:
      context: ./backend/user_auth_service
    container_name: user_auth_service
    depends_on:
      user_auth_db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: user_auth_db
    ports:
      - "8000:8000"
    volumes:
      - ./backend/user_auth_service:/app

  event_ticketing_service:
    build:
      context: ./backend/event_ticketing_service
    container_name: event_ticketing_service
    depends_on:
      event_ticketing_db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: event_ticketing_db
    ports:
      - "8001:8001"
    volumes:
      - ./backend/event_ticketing_service:/app
