version: '3.1'

services:
  db_event_ticketing:
    image: postgres:latest
    container_name: postgres-resellio-event-ticketing
    volumes:
      - ./sql/tables:/sql_tables
      - ./sql/initdb:/docker-entrypoint-initdb.d
      - ./tmp/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: resellio_db
    ports:
      - "5433:5432"
