terraform {
  backend "s3" {
    # All values will be populated using 'terraform init -backend-config=backend_config.json' (generated by running terraform in bootstrap folder)
    # This should only be used for the initial setup of the backend ONCE
  }
}
