name: Run Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    name: "Backend Python Tests"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Make scripts executable
      run: chmod +x ./scripts/utils/print.bash ./scripts/actions/run_tests.bash

    - name: Create .env file for Docker Compose
      run: |
        echo "Creating .env file from template..."
        cp .env.template .env
        echo ".env file created."

    - name: Run Backend API tests
      run: ./scripts/actions/run_tests.bash backend local

    - name: Show logs on failure
      if: failure()
      run: echo "Test script failed. Logs were part of the script output."

  frontend-tests:
    runs-on: ubuntu-latest
    name: "Frontend Flutter Tests"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Make scripts executable
      run: chmod +x ./scripts/utils/print.bash ./scripts/actions/run_tests.bash

    - name: Create .env file for Docker Compose
      run: |
        echo "Creating .env file from template..."
        cp .env.template .env
        echo ".env file created."

    - name: Run Frontend (Flutter) tests via Docker Compose
      # This single command handles Docker startup, testing, and shutdown
      run: ./scripts/actions/run_tests.bash frontend local

    - name: Show logs on failure
      if: failure()
      run: echo "Test script failed. Logs were part of the script output."
